version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - GENERIC_TIMEZONE=Africa/Kigali
    volumes:
      - n8n_data:/home/node/.n8n

  mcp:
    image: gyoridavid/short-video-maker:latest-tiny
    restart: always
    ports:
      - "3123:3123"
    environment:
      - LOG_LEVEL=debug
      - PEXELS_API_KEY=3tnRS1UdvzCQlQICXkw7NwP7pdSKbq6QflazbnlNXFN0I2D689Fb5nZ6

volumes:
  n8n_data:
