version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_PORT=5678
      - N8N_SECURE_COOKIE=false
      - N8N_HOST=0.0.0.0
      - N8N_PROTOCOL=http
      - WEBHOOK_TUNNEL_URL=http://localhost:5678
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

  mcp:
    image: gyoridavid/short-video-maker:latest-tiny
    container_name: mcp
    ports:
      - "3123:3123"
    environment:
      LOG_LEVEL: debug
      PEXELS_API_KEY: 3tnRS1UdvzCQlQICXkw7NwP7pdSKbq6QflazbnlNXFN0I2D689Fb5nZ6
    restart: unless-stopped

volumes:
  n8n_data:
